---
# 在宿主机上启动 binary 或者是 docker
deployment_method: binary

#目标机系统自带Python版本
self_python_version: 3.6.9

# 检查服务的状态
check_service_status: true

# consul的 key-value 选项 
storage_ip: testdatacenter.datumtechs.com
storage_port: 8080

# #### 下面的变量不建议用户修改 ####

# carrier 服务连接进datum网络时优先连接的引导节点的nodeId数组 (enr前缀格式)
# bootstrap_nodes: []

# 服务静态文件下载 url
download_url: "http://testdownload.datumtechs.com/datum/0.5.0/"
consul_download_url: "https://releases.hashicorp.com/consul/1.10.4/consul_1.10.4_linux_amd64.zip"

# 证书文件，非必改目录
ice_via_cert_dir:   "{{ playbook_dir }}/config/ice_via_cert"
carrier_cert_dir:   "{{ playbook_dir }}/config/carrier_cert"
admin_cert_dir:   "{{ playbook_dir }}/config/admin_cert"
scan_cert_dir:   "{{ playbook_dir }}/config/scan_cert"
storage_cert_dir:   "{{ playbook_dir }}/config/storage_cert"
compute_cert_dir:   "{{ playbook_dir }}/config/compute_cert"
data_cert_dir:   "{{ playbook_dir }}/config/data_cert"

# #### 下面的变量不能进行更改 #### 

# 公共变量
listen_all_ip: 0.0.0.0
carrier_pprof_ip: "{{ listen_all_ip }}"
carrier_rpc_ip: "{{ listen_all_ip }}"
carrier_grpc_gateway_ip: "{{ listen_all_ip }}"
carrier_p2p_listen_ip: "{{ listen_all_ip }}"

# 文件下载目录，非必改变量
downloads_dir: "{{ playbook_dir }}/downloads"
avx2: "{{ downloads_dir }}/avx2"
no_avx2: "{{ downloads_dir }}/no_avx2"

# 目标主机文件安装目录
deploy_dir: "/home/{{ansible_ssh_user}}"

# consul agent 信息
consul_zip_name: "{{ consul_download_url.split('/')[-1] | trim }}"
consul_number_int: "{{ groups['consul'] | length | int}}"
consul_leader_ip: "{{ groups['consul'][0] }}"
consul_leader_port: "{{ consul_http_port[0] }}"
consul_leader_serf_lan_port: "{{ consul_serf_lan_port[0] }}"
consul_http_port_self:   "{% set consul_number_int = consul_number_int | int %}
                          {% for i in range(consul_number_int) %}
                              {% if groups['consul'][i] == inventory_hostname %}
                                {{consul_http_port[i] |int}}
                              {% endif %}
                          {% endfor %}"

# data 相关信息
data_port_self: "{% set data_number_int = groups['data'] | length |int %} 
                  {% for i in range(data_number_int) %}
                    {% if groups['data'][i] == inventory_hostname %}
                      {{data_port[i] |int}}  
                    {% endif %}
                  {% endfor %}"

# compute 相关信息
compute_port_self: "{% set compute_number_int = groups['compute'] | length |int %} 
                    {% for i in range(compute_number_int) %}
                      {% if groups['compute'][i] == inventory_hostname %}
                        {{compute_port[i] |int}}  
                      {% endif %}
                    {% endfor %}"


#admin web pinata 配置
#pinata的上传文件的接口地址，用于上传ipfs图片
pinata_url: https://api.pinata.cloud/
#凭证工厂合约地址(20Factory)
data_token_factory_address: '0x981850deE5F18B57DfefC7Df1dB37D9485720447'
#router合约地址(dex router合约)
dex_router_address: '0x0B96629D683bD184Fe183EDB74CF5a4c42375070'
#dex链接地址
dex_web_url: https://test.dipoleswap.exchange/swap
#网络名称
chain_name: PlatON开发网
#链 ID
chain_id: 2206132
#链rpcUrl，给用户使用，必须是外部ip
rpc_url: https://devnet2openapi.platon.network/rpc
#货币符号
symbol: LAT
#区块浏览器
block_explorer_url: https://devnet2scan.platon.network/
#钱包地址前缀hrp
hrp: lat
#链rpcUrl，主要是给后台系统用，可以是内部IP
rpc_url_list: https://devnet2openapi.platon.network/rpc
#有属性凭证工厂合约地址(721Factory)
attribute_data_token_factory_address: '0x25B08817d98AE15F30a33fa720e9d990812363b7'
#有属性凭证交易所地址，格式为<交易所名称,交易所地址>，多个交易所以英文逗号分割
attribute_data_token_exchange: <tofunft交易所|https://tofunft.com/>
#投票合约合约地址,需要用单引号括起来 (Vote合约)
vote_contract_address: '0x67257C7412A2680daF32FA880aE8CB8cb757702c'
#投票合约部署的区块，这个配置决定了事件从哪个区块开始读取
vote_contract_deploy_bn: 11030433
