---

# 销毁集群
- hosts: carrier
  tags:
    - carrier_service
  tasks:
    - name: Clear the exited carrier container and carrier image
      become: True
      become_method: sudo
      shell: "docker stop {{ item.service }}; docker rm {{ item.service }};
        docker rmi `docker images | grep {{ item.name }} | grep {{ item.tag }} | awk '{print $3}'`"
      register: result
      when: enable_deploy_carrier|default(false)
      # rc=1：shell isn't exist
      failed_when: result.rc != 0 and result.rc != 1
      changed_when: false
      with_items: "{{ carrier_image }}"

    - name: Clear the carrier directory 
      become: True
      become_method: sudo
      file:
        path: "{{ deploy_dir }}/{{carrier_dir_name}}"
        state: absent
      when: enable_deploy_carrier|default(false)

- hosts: admin
  tags:
    - admin_service
  tasks:
    - name: Clear the exited mysql container and mysql image
      become: True
      become_method: sudo
      shell: "docker stop {{ item.service }}; docker rm {{ item.service }}; 
        docker rmi `docker images | grep {{ item.name }} | grep {{ item.tag }} | awk '{print $3}'`"
      register: result
      when: enable_deploy_admin|default(false)
      # rc=1：shell isn't exist
      failed_when: result.rc != 0 and result.rc != 1
      changed_when: false
      with_items: "{{ mysql_image }}"

    - name: Clear the exited admin container and admin image
      become: True
      become_method: sudo
      shell: "docker stop {{ item.service }}; docker rm {{ item.service }};
        docker rmi `docker images | grep {{ item.name }} | grep {{ item.tag }} | awk '{print $3}'`"
      register: result
      when: enable_deploy_admin|default(false)
      # rc=1：shell isn't exist
      failed_when: result.rc != 0 and result.rc != 1
      changed_when: false
      with_items: "{{ admin_image }}"

    - name: Clear the admin directory 
      become: True
      become_method: sudo
      file:
        path: "{{ deploy_dir }}/{{admin_dir_name}}"
        state: absent
      when: enable_deploy_admin|default(false)

- hosts: ice_via
  tags:
    - ice_via_service
  tasks:
    - name: Clear the exited ice_via container and ice_via image
      become: True
      become_method: sudo
      shell: "docker stop {{ item.services.ice_via }}; docker rm {{ item.services.ice_via }};
        docker rmi `docker images | grep {{ item.name }} | grep {{ item.tag }} | awk '{print $3}'`"
      register: result
      when: enable_deploy_ice_via|default(false)
      # rc=1：shell isn't exist
      failed_when: result.rc != 0 and result.rc != 1
      changed_when: false
      with_items: "{{ ice_via_consul_image }}"

    - name: Clear the ice_via directory 
      become: True
      become_method: sudo
      file:
        path: "{{ deploy_dir }}/{{ice_via_local_path}}"
        state: absent
      when: enable_deploy_ice_via|default(false)

    - name: If there are no ice_via and consul service directories, clear the ice_via_consul directory.
      become: True
      become_method: sudo
      shell: "[ ! -d {{ deploy_dir }}/{{ice_via_local_path}} ] && 
        [ ! -d {{ deploy_dir }}/{{consul_local_path}} ] && rm -rf {{ deploy_dir }}/{{ice_via_consul_dir_name}}"
      register: result
      when: enable_deploy_ice_via|default(false) and enable_deploy_consul|default(false)
      failed_when: result.rc != 0 and result.rc != 1
      changed_when: false

- hosts: data
  tags:
    - data_service
  tasks:
    - name: Clear the exited fighter_data container and fighter image
      become: True
      become_method: sudo
      shell: "docker stop {{ item.services.data }}; docker rm {{ item.services.data }}; 
        docker rmi `docker images | grep {{ item.name }} | grep {{ item.tag }} | awk '{print $3}'`"
      register: result
      when: enable_deploy_data|default(false)
      # rc=1：shell isn't exist
      failed_when: result.rc != 0 and result.rc != 1
      changed_when: false
      with_items: "{{ fighter_image }}"

    - name: Clear the carrier directory 
      become: True
      become_method: sudo
      file:
        path: "{{ deploy_dir }}/{{data_local_path}}"
        state: absent
      when: enable_deploy_data|default(false)

    - name: If there are no data and compute service directories, clear the fighter directory.
      become: True
      become_method: sudo
      shell: "[ ! -d {{ deploy_dir }}/{{compute_local_path}} ] && 
        [ ! -d {{ deploy_dir }}/{{data_local_path}} ] && rm -rf {{ deploy_dir }}/{{fighter_dir_name}}"
      register: result
      when: enable_deploy_compute|default(false) and enable_deploy_data|default(false)
      failed_when: result.rc != 0 and result.rc != 1
      changed_when: false

- hosts: compute
  tags:
    - compute_service
  tasks:
    - name: Clear the exited fighter_compute container and fighter image
      become: True
      become_method: sudo
      shell: "docker stop {{ item.services.compute }}; docker rm {{ item.services.compute }};
        docker rmi `docker images | grep {{ item.name }} | grep {{ item.tag }} | awk '{print $3}'`"
      register: result
      when: enable_deploy_compute|default(false)
      # rc=1：shell isn't exist
      failed_when: result.rc != 0 and result.rc != 1
      changed_when: false
      with_items: "{{ fighter_image }}"

    - name: Clear the compute directory 
      become: True
      become_method: sudo
      file:
        path: "{{ deploy_dir }}/{{compute_local_path}}"
        state: absent
      when: enable_deploy_compute|default(false)

    - name: If there are no data and compute service directories, clear the fighter directory.
      become: True
      become_method: sudo
      shell: "[ ! -d {{ deploy_dir }}/{{compute_local_path}} ] && 
        [ ! -d {{ deploy_dir }}/{{data_local_path}} ] && rm -rf {{ deploy_dir }}/{{fighter_dir_name}}"
      register: result
      when: enable_deploy_compute|default(false) and enable_deploy_data|default(false)
      failed_when: result.rc != 0 and result.rc != 1
      changed_when: false

- hosts: consul
  tags:
    - consul_service
  tasks:
    - name: Clear the exited consul container and consul image
      become: True
      become_method: sudo
      shell: "docker stop {{ item.services.consul }}; docker rm {{ item.services.consul }};
        docker rmi `docker images | grep {{ item.name }} | grep {{ item.tag }} | awk '{print $3}'`"
      register: result
      when: enable_deploy_consul|default(false)
      # rc=1：shell isn't exist
      failed_when: result.rc != 0 and result.rc != 1
      changed_when: false
      with_items: "{{ ice_via_consul_image }}"

    - name: Clear the consul directory 
      become: True
      become_method: sudo
      file:
        path: "{{ deploy_dir }}/{{consul_local_path}}"
        state: absent
      when: enable_deploy_consul|default(false)

    - name: If there are no ice_via and consul service directories, clear the ice_via_consul directory.
      become: True
      become_method: sudo
      shell: "[ ! -d {{ deploy_dir }}/{{ice_via_local_path}} ] && 
        [ ! -d {{ deploy_dir }}/{{consul_local_path}} ] && rm -rf {{ deploy_dir }}/{{ice_via_consul_dir_name}}"
      register: result
      when: enable_deploy_ice_via|default(false) and enable_deploy_consul|default(false)
      failed_when: result.rc != 0 and result.rc != 1
      changed_when: false
      