# ---

# 停止所有服务
- name: stop ice via
  hosts: ice_via
  tags:
    - ice_via
  tasks:
    - name: stop ice_via service
      become: True
      become_method: sudo
      shell: docker stop {{ item.services.ice_via }}
      register: result
      changed_when: false
      failed_when: result.rc != 0 and result.rc != 1
      when: enable_deploy_ice_via|default(false)
      with_items: "{{ ice_via_consul_image }}"

    - name: wait until the IceGrid port is down
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ ice_grid_port }}"
        state: stopped
        msg: "the pump port {{ ice_grid_port }} is not down"
        timeout: "{{wait_for_timeout|int}}"
      when: enable_deploy_ice_via|default(false)

    - name: wait until the Glacier2 port is down
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ ice_glacier2_port }}"
        state: stopped
        msg: "the pump port {{ ice_glacier2_port }} is not down"
        timeout: "{{wait_for_timeout|int}}"
      when: enable_deploy_ice_via|default(false)

- name: stop carrier
  hosts: carrier
  tags:
    - carrier
  tasks:
    - name: stop carrier
      become: True
      become_method: sudo
      shell: docker stop {{ item.service }}
      register: result
      changed_when: false
      failed_when: result.rc != 0 and result.rc != 1
      when: enable_deploy_carrier|default(false)
      with_items: "{{ carrier_image }}"

    - name: wait until the carrier_rpc_port is down
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ carrier_rpc_port }}"
        state: stopped
        msg: "the pump port {{ carrier_rpc_port }} is not down"
        timeout: "{{wait_for_timeout|int}}"
      when: enable_deploy_carrier|default(false)

- name: stop admin
  hosts: admin
  tags:
    - admin
  tasks:
    - name: stop admin
      become: True
      become_method: sudo
      shell: docker stop {{ item.service }}
      register: result
      changed_when: false
      failed_when: result.rc != 0 and result.rc != 1
      when: enable_deploy_admin|default(false)
      with_items: "{{ admin_image }}"

    - name: wait until the admin_web_port is down
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ admin_web_port }}"
        state: stopped
        msg: "the pump port {{ admin_web_port }} is not down"
        timeout: "{{wait_for_timeout|int}}"
      when: enable_deploy_admin|default(false)

    - name: stop mysql
      become: True
      become_method: sudo
      shell: docker stop {{ item.service }}
      register: result
      changed_when: false
      failed_when: result.rc != 0 and result.rc != 1
      when: enable_deploy_admin|default(false)
      with_items: "{{ mysql_image }}"

    - name: wait until the mysql_listen_port is down
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ mysql_listen_port }}"
        state: stopped
        msg: "the pump port {{ mysql_listen_port }} is not down"
        timeout: "{{wait_for_timeout|int}}"
      when: enable_deploy_admin|default(false)

- name: stop data
  hosts: data
  tags:
    - data
  tasks:
    - name: stop data
      become: True
      become_method: sudo
      shell: docker stop {{ item.services.data }}
      register: result
      changed_when: false
      failed_when: result.rc != 0 and result.rc != 1
      when: enable_deploy_data|default(false)
      with_items: "{{ fighter_image }}"

    - name: wait until the data port is down
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ data_port_self }}"
        state: stopped
        msg: "the pump port {{ data_port_self }} is not down"
        timeout: "{{wait_for_timeout|int}}"
      when: enable_deploy_data|default(false)

- name: stop compute
  hosts: compute
  tags:
    - compute
  tasks:
    - name: stop compute
      become: True
      become_method: sudo
      shell: docker stop {{ item.services.compute }}
      register: result
      changed_when: false
      failed_when: result.rc != 0 and result.rc != 1
      when: enable_deploy_compute|default(false)
      with_items: "{{ fighter_image }}"

    - name: wait until the compute port is down
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ compute_port_self }}"
        state: stopped
        msg: "the pump port {{ compute_port_self }} is not down"
        timeout: "{{wait_for_timeout|int}}"
      when: enable_deploy_compute|default(false)

- name: stop consul
  hosts: consul
  tags:
    - consul
  tasks:
    - name: stop consul service
      become: True
      become_method: sudo
      shell: docker stop {{ item.services.consul }}
      register: result
      changed_when: false
      failed_when: result.rc != 0 and result.rc != 1
      when: enable_deploy_consul|default(false)
      with_items: "{{ ice_via_consul_image }}"
    
    - name: wait until the consul http port is down
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ consul_http_port_self | trim }}"
        state: stopped
        msg: "the pump port {{ consul_http_port_self | trim }} is not down"
      when: enable_deploy_consul|default(false)
